---
apiVersion: skaffold/v2beta16
kind: Config

build:
  artifacts:
  - image: config-reloader-sidecar
    custom:
      buildCommand: docker buildx build . --platform linux/amd64,linux/arm64 -f Dockerfile -t "$IMAGE" $(if [ "$PUSH_IMAGE" = "true" ]; then echo "--push"; else echo "--load"; fi)
      dependencies:
        paths:
        - .

profiles:
- name: shared
  build:
    artifacts:
    - image: config-reloader-sidecar
      custom:
        buildCommand: docker buildx build .  -f Dockerfile -t "$IMAGE" $(if [ "$PUSH_IMAGE" = "true" ]; then echo "--push"; else echo "--load"; fi)
        dependencies:
          paths:
          - .
